// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EShopFashion.Entities
{
    public partial class Tb1CartStatus
    {
        public int CartStatusId { get; set; }
        public string CartStatus { get; set; }
    }
}